<table class="data table" id="custom-config-table">
    <thead>
        <tr>
            <th>Parent Key</th>
            <th>Key</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($block->flattenConfigArray($block->getConfigArray()) as $data): ?>
            <tr>
                <td><?= $data['parent_key'] ?></td>
                <td><?= $data['key'] ?></td>
                <td><?= $data['value'] ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
<style>
    /* Style for the table */
.data.table {
    width: 100%;
    border-collapse: collapse;
    margin-bottom: 20px;
    background-color: #fff;
    border: 1px solid #ddd;
}

/* Style for table headers */
.data.table th {
    background-color: #f2f2f2;
    text-align: left;
    padding: 10px;
    border: 1px solid #ddd;
}

/* Style for table rows */
.data.table td {
    padding: 10px;
    border: 1px solid #ddd;
}

/* Style for alternating row background color */
.data.table tbody tr:nth-child(even) {
    background-color: #f2f2f2;
}

</style>
