<p>Last Execution Time: <?= $block->getLastExecutionTime() ?></p>
<table class="data table" id="custom-config-table">
    <thead>
        <tr>
            <th>Parent Key</th>
            <th>Key</th>
            <th>Value</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach ($block->flattenConfigArray($block->getConfigArray()) as $data): ?>
            <tr>
                <td><?= $data['parent_key'] ?></td>
                <td><?= $data['key'] ?></td>
                <td><?= $data['value'] ?></td>
            </tr>
        <?php endforeach; ?>
    </tbody>
</table>
